function criticNetwork = localCreateCriticNetwork(ObsInfo,numActions,nNN)
NumHiddenUnitC=nNN;   
DltInputDimension= prod(ObsInfo.Dimension);
criticnet_default=[featureInputLayer(DltInputDimension,'Name', 'input_1'), ...
                        fullyConnectedLayer(NumHiddenUnitC, 'Name', 'fc_1','WeightsInitializer','he','BiasInitializer','zeros'), ...
                        reluLayer('Name','relu_body'),...
                        fullyConnectedLayer(NumHiddenUnitC, 'Name', 'fc_2','WeightsInitializer','he','BiasInitializer','zeros'), ...
                        reluLayer('Name','relu_body2'),...
                        fullyConnectedLayer(1, 'Name', 'output','WeightsInitializer','he','BiasInitializer','zeros')]; %fullyConnectedLayer(NumHiddenUnitC, 'Name', 'fc_2'), ...
                                                                   %reluLayer('Name','relu_body2'),...                        
                        
        
criticNetdefault=layerGraph(criticnet_default);
criticNetwork=criticNetdefault;

end 